version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/DockerFile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/face_recognition_local
      - REDIS_URL=redis://redis:6379
      - UPLOAD_PATH=/app/uploads
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - db
      - redis
    networks:
      - face-net

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=face_recognition_local
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - face-net

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - face-net

volumes:
  postgres_data:

networks:
  face-net:
    driver: bridge